CREATE TABLE "user" (
	USER_ID SERIAL PRIMARY KEY NOT NULL,
	NAMES VARCHAR(128) NOT NULL,
	LAST_NAMES VARCHAR(128) NOT NULL,
	USER_NAME VARCHAR(128) NOT NULL,
	EMAIL_ADDRESS VARCHAR(128) UNIQUE NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL
);

CREATE TYPE INVESTMENT_TYPE AS ENUM ('fija','variable');

CREATE TABLE CURRENCY (
	CURRENCY_ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(128) NOT NULL,
	VALUE INTEGER NOT NULL,
	USER_ID INTEGER,
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES "user"(USER_ID)
);

CREATE TABLE INVESTMENT (
	INVESTMENT_ID SERIAL PRIMARY KEY NOT NULL,
	DESCRIPTION VARCHAR(128) NOT NULL,
	QUANTITY INTEGER NOT NULL,
	PRICE INTEGER NOT NULL,
	TYPE_OF_INVESTMENT INVESTMENT_TYPE NOT NULL,
	CURRENCY_ID INTEGER,
	USER_ID INTEGER,
	CONSTRAINT FK_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(CURRENCY_ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES "user"(USER_ID)
);